import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationHeader from "../components/NavigationHeader";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brainrust",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationHeader />
        {children}
      </body>
    </html>
  );
}
